### ISSUE TITLE
Refactor API Input and Output Structure

### ISSUE THREAD

**Issue by stefan-esquivel** [SENG499-COMPANY4/Algorithm-2#52]
## Objective:
This issue aims to refactor the current API input and output structure for better alignment with the data model. Additionally, this issue will introduce a `.api` file in the repository, which will contain the current specification of our API. This file should be version-controlled, and any changes to the API should be made through PRs.

### Input:
```json
[
    {
        "course": "string",
        "prerequisites": ["string"],
        "corequisites": ["string"],
        "pastEnrollment": [
            {
                "year": "int",
                "term": "int",
                "size": "int"
            }
        ]
    }
]
```
### Output:
```json
[
    {
        "course": "string",
        "size": "int",
        "constraints": ["string"],
        "term": "int"
    }
]
```

### Input:
```json
[
    {
        "course": "string",
        "Term": ["int"],
        "Year": "int",
        "pastEnrollment": [
            {
                "year": "int",
                "term": "int",
                "size": "int"
            }
        ]
    }
]
```
### Output:
```json
[
    {
        "course": "string",
        "size": "int",
        "term": "int"
    }
]
```

## Tasks:

- [ ] Refactor the ~~API~~ algorithm to accept the new input structure.
- [ ] Refactor the ~~API~~ algorithm to produce the new output structure.
- [ ] ~~Create a `.api` file containing the specification of our API.~~
- [ ] ~~Update the documentation to reflect these changes.~~
- [ ] ~~Implement CI checks to ensure `.api` file is updated with API changes.~~
- [x] Update test data to match input API format

## Reason for Change:

The change is aimed at simplifying the data structure and making it more consistent with our current data model. By doing this, we can ensure better data integrity and easier maintenance.

## Additional Information:

Please make sure to thoroughly test the refactored API to ensure that it behaves as expected. If there are any questions or clarifications needed, feel free to comment on this issue.

**Comment by D-Aldana** [comment]
I'll make sure the code does stuff correctly :)
