### ISSUE TITLE
Retrieve and Structure Class Count Data as JSON from Backend

### ISSUE THREAD

**Issue by stefan-esquivel** [SENG499-COMPANY4/Algorithm-2#57]
## Objective:
The goal of this issue is to establish a connection to the backend, retrieve the class count data, and structure it in a specified JSON format. This is required for testing purposes to ensure that the data received from the backend is consistent with the expected structure and content.

## Expected JSON Format:

The data should be structured in the following JSON format:

```json
[
    {
        "course": "string",
        "Term": [integer],
        "Year": integer,
        "pastEnrollment": [
            {
                "year": integer,
                "term": integer,
                "size": integer
            }
        ]
    }
]
```

## Key Components:

1. `course`: A string representing the course name/code.
2. `Term`: An array of integers representing the term(s) for which data is being fetched.
3. `Year`: An integer representing the year for which data is being fetched.
4. `pastEnrollment`: An array of objects, where each object contains:
    - `year`: An integer representing the year of past enrollment.
    - `term`: An integer representing the term of past enrollment.
    - `size`: An integer representing the size of the class in that term.

## Tasks:

- [ ] Establish a connection to the backend/database.
- [ ] Retrieve all relevant class count data from the database.
- [x] Structure the data in the aforementioned JSON format.
- [x] Validate the structured data against the expected JSON format.
- [ ] Document any discrepancies or issues identified during testing.

## Additional Information:

Please ensure the security and integrity of the data during retrieval and processing. If there are any questions or clarifications needed, feel free to comment on this issue.
